# Generated by Django 5.2.1 on 2025-05-19 10:04

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chantier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom du chantier')),
                ('maitre_ouvrage', models.CharField(max_length=255)),
                ('entreprise_terrassement', models.CharField(max_length=255)),
                ('localisation', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Chantier',
                'verbose_name_plural': 'Chantiers',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('exploitant', 'Exploitant'), ('entreprise', 'Entreprise'), ('client', 'Client')], max_length=20)),
                ('company_name', models.CharField(max_length=255, verbose_name="Nom de l'entreprise")),
                ('siret_number', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='SIRET')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Code postal')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pays')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Téléphone')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Compost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fournisseur', models.CharField(max_length=255)),
                ('date_reception', models.DateField()),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_compost', models.CharField(max_length=100)),
                ('localisation', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composts', to='core.chantier')),
            ],
            options={
                'verbose_name': 'Compost',
                'verbose_name_plural': 'Composts',
                'ordering': ['-date_reception'],
            },
        ),
        migrations.CreateModel(
            name='Gisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commune', models.CharField(max_length=100)),
                ('periode_terrassement', models.CharField(max_length=100)),
                ('volume_terrasse', models.DecimalField(decimal_places=2, max_digits=10)),
                ('materiau', models.CharField(max_length=255)),
                ('localisation', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gisements', to='core.chantier')),
            ],
            options={
                'verbose_name': 'Gisement',
                'verbose_name_plural': 'Gisements',
                'ordering': ['-periode_terrassement'],
            },
        ),
        migrations.CreateModel(
            name='Melange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_produit', models.CharField(editable=False, max_length=100, unique=True)),
                ('site_stockage', models.CharField(max_length=255)),
                ('fournisseur', models.CharField(max_length=255)),
                ('couverture_vegetale', models.CharField(blank=True, max_length=100, null=True)),
                ('periode_melange', models.CharField(max_length=100)),
                ('date_semis', models.DateField(blank=True, null=True)),
                ('references_analyses', models.TextField(blank=True, null=True)),
                ('chantier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.chantier')),
            ],
            options={
                'verbose_name': 'Mélange',
                'verbose_name_plural': 'Mélanges',
                'ordering': ['-periode_melange'],
            },
        ),
        migrations.CreateModel(
            name='ProduitVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_produit', models.CharField(editable=False, max_length=100, unique=True)),
                ('fournisseur', models.CharField(max_length=255)),
                ('nom_site', models.CharField(max_length=255)),
                ('volume_initial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume_disponible', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_disponibilite', models.DateField()),
                ('commentaires_analyses', models.TextField(blank=True, null=True)),
                ('volume_vendu', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('acheteur', models.CharField(blank=True, max_length=255, null=True)),
                ('date_achat', models.DateField(blank=True, null=True)),
                ('periode_destockage', models.CharField(blank=True, max_length=100, null=True)),
                ('localisation_projet', models.CharField(blank=True, max_length=255, null=True)),
                ('chantier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.chantier')),
                ('melange', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.melange')),
            ],
            options={
                'verbose_name': 'Produit de vente',
                'verbose_name_plural': 'Produits de vente',
                'ordering': ['-date_disponibilite'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fichier', models.CharField(max_length=255)),
                ('fichier', models.FileField(upload_to='documents/')),
                ('type_document', models.CharField(choices=[('fiche_produit', 'Fiche produit'), ('radar', 'Radar produit'), ('analyse', 'Analyse laboratoire'), ('description_sol', 'Fiche description sol'), ('protocole', 'Protocole d’échantillonnage'), ('autre', 'Autre')], max_length=100)),
                ('date_ajout', models.DateField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.produitvente')),
            ],
            options={
                'verbose_name': 'Document technique',
                'verbose_name_plural': 'Documents techniques',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='AnalyseLaboratoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laboratoire', models.CharField(max_length=255)),
                ('code_rapport', models.CharField(max_length=100)),
                ('date_reception', models.DateField()),
                ('date_analyse', models.DateField()),
                ('profondeur_prelevement', models.CharField(blank=True, max_length=100, null=True)),
                ('localisation_echantillon', models.CharField(blank=True, max_length=255, null=True)),
                ('ph_eau', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ph_kcl', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('calcaire_total', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('calcaire_actif', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('conductivite', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('matiere_organique', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('azote_total', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('c_n', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Rapport C/N')),
                ('cec', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='CEC (meq/100g)')),
                ('saturation', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taux de saturation (%)')),
                ('argile', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('limons_fins', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('limons_grossiers', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sables_fins', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sables_grossiers', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('calcium', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('magnesium', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('potassium', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('phosphore', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='P2O5 (mg/kg)')),
                ('fer', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cuivre', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('zinc', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('manganese', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('densite_apparente', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('porosite_totale', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('porosite_drainage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('eau_capillaire', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('permeabilite', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Perméabilité (cm/h)')),
                ('iam', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Intensité activité microbienne')),
                ('refus_gravier_2mm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Refus gravier (>2mm, %)')),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='core.produitvente')),
            ],
            options={
                'verbose_name': 'Analyse de laboratoire',
                'verbose_name_plural': 'Analyses de laboratoire',
                'ordering': ['-date_analyse'],
            },
        ),
    ]
