# Generated by Django 5.2.1 on 2025-05-19 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='analyselaboratoire',
            table='analyse_laboratoire',
        ),
        migrations.AlterModelTable(
            name='chantier',
            table='chantier',
        ),
        migrations.AlterModelTable(
            name='compost',
            table='compost',
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='utilisateur',
        ),
        migrations.AlterModelTable(
            name='documenttechnique',
            table='document_technique',
        ),
        migrations.AlterModelTable(
            name='gisement',
            table='gisement',
        ),
        migrations.AlterModelTable(
            name='melange',
            table='melange',
        ),
        migrations.AlterModelTable(
            name='produitvente',
            table='produit_vente',
        ),
    ]
