# Generated by Django 5.2.1 on 2025-07-15 10:00

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chantier',
            name='date_creation',
            field=models.DateField(default=core.models.today),
        ),
        migrations.AlterField(
            model_name='melange',
            name='date_creation',
            field=models.DateField(default=core.models.today),
        ),
        migrations.AlterField(
            model_name='melange',
            name='date_semis',
            field=models.DateField(default=core.models.today),
        ),
    ]
