# Generated by Django 5.2.1 on 2025-06-14 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='melange',
            name='etat',
            field=models.IntegerField(choices=[(1, 'Composition'), (2, 'Ordre de conformité'), (3, 'Consignes de mélange'), (4, 'Contrôle +1 mois'), (5, 'Contrôle +2 mois'), (6, 'Validation finale (Fiche technique)')], default=1),
        ),
    ]
