# Generated by Django 5.2.1 on 2025-07-15 12:17

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_chantier_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gisement',
            name='date_creation',
            field=models.DateField(default=core.models.today, help_text='Date de création du gisement'),
        ),
        migrations.AlterField(
            model_name='produitvente',
            name='commentaires_analyses',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produitvente',
            name='date_disponibilite',
            field=models.DateField(default=core.models.today),
        ),
        migrations.AlterField(
            model_name='produitvente',
            name='nom_site',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
