# Generated by Django 5.2.1 on 2025-05-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_analyselaboratoire_table_alter_chantier_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyselaboratoire',
            name='fichier_pdf',
            field=models.FileField(blank=True, null=True, upload_to='uploads/pdf/'),
        ),
    ]
