# Generated by Django 5.2.1 on 2025-06-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_melange_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='melange',
            name='consignes_melange',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='melange',
            name='controle_1',
            field=models.TextField(blank=True, null=True, verbose_name='Rapport +1 mois'),
        ),
        migrations.AddField(
            model_name='melange',
            name='controle_2',
            field=models.TextField(blank=True, null=True, verbose_name='Rapport +2 mois'),
        ),
        migrations.AddField(
            model_name='melange',
            name='fiche_technique',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='melange',
            name='ordre_conformite',
            field=models.TextField(blank=True, null=True),
        ),
    ]
