# Generated by Django 5.2.1 on 2025-05-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_analyselaboratoire_fichier_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyselaboratoire',
            name='fichier_pdf',
            field=models.FileField(blank=True, null=True, upload_to='uploads/analyse_pdfs/'),
        ),
    ]
