# Generated by Django 5.2.1 on 2025-07-22 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_gisement_date_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitvente',
            name='pret_pour_vente',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DocumentProduitVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('FTP', 'Fiche technique produit'), ('ANALYSE', 'Analyse'), ('SUIVI', 'Suivi visuel'), ('AUTRE', 'Autre document de traçabilité')], max_length=50)),
                ('fichier', models.FileField(upload_to='documents_produits/')),
                ('remarque', models.TextField(blank=True, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_produit_vente', to='core.produitvente')),
            ],
        ),
    ]
