# Generated by Django 5.2.1 on 2025-06-16 22:11

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_melange_consignes_melange_melange_controle_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='melange',
            name='date_creation',
            field=models.DateField(default=core.models.today),
        ),
        migrations.AlterField(
            model_name='melange',
            name='date_semis',
            field=models.DateField(default=core.models.today),
        ),
    ]
