# Generated by Django 5.2.1 on 2025-07-23 09:14

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_produitvente_pret_pour_vente_documentproduitvente'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaisieVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=255)),
                ('volume_tonne', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_vente', models.DateField()),
                ('nom_chantier_recepteur', models.CharField(max_length=255)),
                ('adresse_chantier', models.CharField(max_length=255)),
                ('est_validee', models.BooleanField(default=False, help_text="Indique si la vente a été validée par l'entreprise")),
                ('date_achat', models.DateTimeField(auto_now_add=True)),
                ('date_modification_vente', models.DateTimeField(auto_now=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to='core.produitvente')),
                ('responsable', models.ForeignKey(blank=True, help_text="Responsable automatiquement défini à l'utilisateur connecté.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits_a_vendre', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saisie de vente',
                'verbose_name_plural': 'Saisies de vente',
                'db_table': 'saisie_vente',
                'ordering': ['-date_achat', 'nom_client'],
            },
        ),
        migrations.CreateModel(
            name='ChantierRecepteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('projet_nom', models.CharField(max_length=255, verbose_name='Nom du projet')),
                ('adresse', models.TextField()),
                ('date_creation', models.DateField(default=core.models.today, help_text='Date de création du chantier récepteur')),
                ('date_debut', models.DateField(blank=True, help_text='Date de début du chantier récepteur', null=True)),
                ('date_fin', models.DateField(blank=True, help_text='Date de fin du chantier récepteur', null=True)),
                ('volume_receptionne', models.DecimalField(blank=True, decimal_places=2, help_text='Volume de matériau réceptionné sur le chantier récepteur', max_digits=10, null=True)),
                ('volume_restant', models.DecimalField(blank=True, decimal_places=2, help_text='Volume restant à réceptionner sur le chantier récepteur', max_digits=10, null=True)),
                ('prix', models.DecimalField(blank=True, decimal_places=2, help_text='Prix du chantier récepteur', max_digits=10, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='en_attente', max_length=20)),
                ('responsable', models.ForeignKey(blank=True, help_text="Responsable automatiquement défini à l'utilisateur connecté.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chantiers_recepteurs', to=settings.AUTH_USER_MODEL)),
                ('vente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chantier_recepteur', to='core.saisievente')),
            ],
            options={
                'verbose_name': 'Chantier récepteur',
                'verbose_name_plural': 'Chantiers récepteurs',
                'db_table': 'chantier_recepteur',
                'ordering': ['-date_creation', 'nom'],
            },
        ),
    ]
