# Generated by Django 5.2.1 on 2025-05-27 08:57

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_analyselaboratoire_fichier_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentGisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fichier', models.CharField(max_length=255)),
                ('fichier', models.FileField(blank=True, null=True, upload_to=core.utils.document_upload_path)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('gisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.gisement')),
            ],
            options={
                'db_table': 'document_gisement',
                'ordering': ['-date_ajout'],
            },
        ),
    ]
