# Generated by Django 5.2.1 on 2025-05-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_documentgisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='gisement',
            name='type_de_sol',
            field=models.CharField(choices=[('limon', 'Limon'), ('sableux', 'Sableux'), ('argileux', 'Argileux'), ('caillouteux', 'Caillouteux'), ('autre', 'Autre')], default='limon', max_length=20),
        ),
    ]
