# Generated by Django 5.2.1 on 2025-07-25 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_saisievente_chantierrecepteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chantierrecepteur',
            name='adresse',
            field=models.TextField(help_text='Adresse du chantier récepteur', max_length=500),
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('date_debut', models.DateField()),
                ('duree_jours', models.IntegerField(default=1)),
                ('statut', models.CharField(choices=[('done', 'Terminé'), ('active', 'En cours'), ('planned', 'Planifié')], max_length=50)),
                ('melange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plannings', to='core.melange')),
            ],
        ),
    ]
