# Generated by Django 5.2.1 on 2025-05-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_gisement_type_de_sol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentgisement',
            name='nom_fichier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
