# Generated by Django 5.2.1 on 2025-07-26 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_chantierrecepteur_adresse_planning'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='responsable',
            field=models.ForeignKey(blank=True, help_text="Responsable automatiquement défini à l'utilisateur connecté.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plannings', to=settings.AUTH_USER_MODEL),
        ),
    ]
