# Generated by Django 5.2.1 on 2025-06-05 11:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_documentgisement_nom_fichier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='melange',
            name='chantier',
        ),
        migrations.RemoveField(
            model_name='melange',
            name='site_stockage',
        ),
        migrations.AddField(
            model_name='melange',
            name='date_creation',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='melange',
            name='gisements',
            field=models.ManyToManyField(related_name='melanges', to='core.gisement'),
        ),
        migrations.AddField(
            model_name='melange',
            name='nom',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom du mélange'),
        ),
        migrations.AlterField(
            model_name='melange',
            name='date_semis',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Plateforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Plateforme sans nom')),
                ('localisation', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('date_creation', models.DateField(default=django.utils.timezone.now)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plateformes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plateforme',
                'verbose_name_plural': 'Plateformes',
                'db_table': 'plateforme',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='melange',
            name='plateforme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.plateforme'),
        ),
    ]
