# Generated by Django 5.2.1 on 2025-08-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_planning_responsable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produitvente',
            name='volume_vendu',
        ),
        migrations.AddField(
            model_name='produitvente',
            name='densite',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Densité en tonne/m³', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='saisievente',
            name='voulume_m3',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Volume en m3, calculé automatiquement à partir du volume en tonnes si le produit a une densité connue.', max_digits=10, null=True),
        ),
    ]
