# Generated by Django 5.2.1 on 2025-08-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_produitvente_volume_vendu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produitvente',
            name='densite',
        ),
        migrations.RemoveField(
            model_name='saisievente',
            name='voulume_m3',
        ),
        migrations.AddField(
            model_name='produitvente',
            name='volume_vendu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
