# Generated by Django 5.2.1 on 2025-08-01 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_produitvente_densite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produitvente',
            name='volume_disponible',
        ),
    ]
