# Generated by Django 5.2.1 on 2025-08-28 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_chantier_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chantierrecepteur',
            options={'ordering': ['nom'], 'verbose_name': 'Chantier récepteur', 'verbose_name_plural': 'Chantiers récepteurs'},
        ),
        migrations.RemoveField(
            model_name='chantierrecepteur',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='chantierrecepteur',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='chantierrecepteur',
            name='date_fin',
        ),
        migrations.RemoveField(
            model_name='chantierrecepteur',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='chantierrecepteur',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='chantierrecepteur',
            name='prix',
        ),
        migrations.RemoveField(
            model_name='chantierrecepteur',
            name='projet_nom',
        ),
        migrations.RemoveField(
            model_name='chantierrecepteur',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='chantierrecepteur',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='chantierrecepteur',
            name='vente',
        ),
        migrations.RemoveField(
            model_name='chantierrecepteur',
            name='volume_receptionne',
        ),
        migrations.RemoveField(
            model_name='chantierrecepteur',
            name='volume_restant',
        ),
        migrations.AddField(
            model_name='saisievente',
            name='chantier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.chantierrecepteur'),
        ),
        migrations.AlterField(
            model_name='chantierrecepteur',
            name='adresse',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='chantierrecepteur',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='saisievente',
            name='responsable',
            field=models.ForeignKey(blank=True, help_text="Responsable automatiquement défini à l'utilisateur connecté.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saisies_ventes', to=settings.AUTH_USER_MODEL),
        ),
    ]
