# Generated by Django 5.2.1 on 2025-09-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_chantierrecepteur_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chantier',
            name='commune',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
