# Generated by Django 5.2.1 on 2025-09-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_chantier_commune'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chantier',
            name='nom',
            field=models.CharField(blank=True, editable=False, help_text='Nom du chantier, généré automatiquement si vide.', max_length=255, null=True, unique=True, verbose_name='Nom du chantier'),
        ),
    ]
