# Generated by Django 5.2.1 on 2025-09-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_chantier_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='plateforme',
            name='entreprise_gestionnaire',
            field=models.CharField(default='', help_text='Entreprise gestionnaire de la plateforme', max_length=255),
        ),
    ]
