# Generated by Django 5.2.1 on 2025-09-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_plateforme_entreprise_gestionnaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitvente',
            name='producteur',
            field=models.CharField(default='', help_text='Producteur du produit de vente', max_length=255),
        ),
    ]
