# Generated by Django 5.2.1 on 2025-09-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_produitvente_producteur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produitvente',
            name='producteur',
        ),
        migrations.AddField(
            model_name='melange',
            name='producteur',
            field=models.CharField(default='', help_text='Producteur du produit de vente', max_length=255),
        ),
    ]
