# Generated by Django 5.2.1 on 2025-09-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_produitvente_producteur_melange_producteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produitvente',
            name='reference_produit',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
