# Generated by Django 5.2.1 on 2025-09-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_produitvente_reference_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plateforme',
            name='entreprise_gestionnaire',
            field=models.CharField(help_text='Entreprise gestionnaire de la plateforme', max_length=255),
        ),
    ]
