# Generated by Django 5.2.1 on 2025-09-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_plateforme_entreprise_gestionnaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plateforme',
            name='entreprise_gestionnaire',
            field=models.CharField(max_length=255),
        ),
    ]
