# Generated by Django 5.2.1 on 2025-10-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_plateforme_entreprise_gestionnaire'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amendementorganique',
            options={'ordering': ['nom'], 'verbose_name': 'Amendement organique', 'verbose_name_plural': 'Amendements organiques'},
        ),
        migrations.RemoveField(
            model_name='amendementorganique',
            name='utilisateur',
        ),
        migrations.AddField(
            model_name='amendementorganique',
            name='commune',
            field=models.CharField(default='LYON', help_text="Commune de provenance de l'émendent organique", max_length=100),
        ),
        migrations.AlterField(
            model_name='amendementorganique',
            name='nom',
            field=models.CharField(default='', editable=False, help_text="Nom de l'émendent organique, généré automatiquement si vide.", max_length=255, unique=True),
        ),
    ]
