# Generated by Django 5.2.1 on 2025-10-01 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_amendementorganique_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amendementorganique',
            name='commune',
            field=models.CharField(default=models.ForeignKey(blank=True, help_text="Plateforme de compostage ou d'émendement associée.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emendements', to='core.plateforme'), help_text="Commune de provenance de l'émendent organique", max_length=100),
        ),
    ]
