# Generated by Django 5.2.1 on 2025-10-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_amendementorganique_commune'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amendementorganique',
            name='commune',
            field=models.CharField(default='LYON', help_text="Commune de provenance de l'émendent organique", max_length=100),
        ),
    ]
