# Generated by Django 5.2.1 on 2025-10-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_amendementorganique_commune'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amendementorganique',
            name='localisation',
            field=models.CharField(blank=True, default=models.CharField(default='LYON', help_text="Commune de provenance de l'émendent organique", max_length=100), max_length=255, null=True),
        ),
    ]
