# Generated by Django 5.2.1 on 2025-10-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_amendementorganique_localisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amendementorganique',
            name='localisation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
