# Generated by Django 5.2.1 on 2025-10-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_amendementorganique_localisation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amendementorganique',
            options={'ordering': ['numero_sequence'], 'verbose_name': 'Amendement organique', 'verbose_name_plural': 'Amendements organiques'},
        ),
        migrations.AddField(
            model_name='amendementorganique',
            name='numero_sequence',
            field=models.IntegerField(default=1, help_text='Numéro séquentiel pour le tri'),
        ),
    ]
