# Generated by Django 5.2.1 on 2025-10-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_amendementorganique_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plateforme',
            options={'ordering': ['numero_sequence'], 'verbose_name': 'Plateforme', 'verbose_name_plural': 'Plateformes'},
        ),
        migrations.AddField(
            model_name='plateforme',
            name='numero_sequence',
            field=models.IntegerField(default=1, editable=False, help_text='Numéro séquentiel pour le tri'),
        ),
        migrations.AlterField(
            model_name='amendementorganique',
            name='numero_sequence',
            field=models.IntegerField(default=1, editable=False, help_text='Numéro séquentiel pour le tri'),
        ),
        migrations.AlterField(
            model_name='plateforme',
            name='nom',
            field=models.CharField(blank=True, editable=False, help_text='Nom de la plateforme, généré automatiquement si vide.', max_length=255, null=True, unique=True),
        ),
    ]
