# Generated by Django 5.2.1 on 2025-10-01 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_plateforme_options_plateforme_numero_sequence_and_more'),
    ]

    operations = [
    ]
