# Generated by Django 5.2.1 on 2025-10-03 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_add_plateforme_sequence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amendementorganique',
            options={'ordering': ['plateforme', 'numero_sequence'], 'verbose_name': 'Amendement organique', 'verbose_name_plural': 'Amendements organiques'},
        ),
        migrations.CreateModel(
            name='SuiviStockPlateforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('andain_numero', models.IntegerField(help_text="Numéro de l'andain sur la plateforme")),
                ('reference_suivi', models.CharField(editable=False, help_text='Référence générée automatiquement', max_length=100, unique=True)),
                ('volume_initial_m3', models.DecimalField(decimal_places=2, help_text='Volume initial en m³', max_digits=10)),
                ('volume_restant_m3', models.DecimalField(decimal_places=2, help_text='Volume restant en m³ (MAJ)', max_digits=10)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('en_culture', 'En culture'), ('pret_vente', 'Prêt pour vente'), ('ecoule', 'Écoulé'), ('suspendu', 'Suspendu')], default='en_cours', help_text="Statut actuel de l'andain", max_length=20)),
                ('date_mise_en_andains', models.DateField(blank=True, help_text='Date de mise en andains', null=True)),
                ('date_mise_en_culture', models.DateField(blank=True, help_text='Date de mise en culture', null=True)),
                ('date_previsionnelle_vente', models.DateField(blank=True, help_text='Date prévisionnelle de mise en vente', null=True)),
                ('date_ecoulement', models.DateField(blank=True, help_text="Date d'écoulement complet", null=True)),
                ('recette', models.TextField(blank=True, help_text='Recette/composition du mélange', null=True)),
                ('remarques', models.TextField(blank=True, help_text='Remarques et observations', null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('melange', models.ForeignKey(help_text='Mélange associé à cet andain', on_delete=django.db.models.deletion.CASCADE, related_name='suivis_stock', to='core.melange')),
                ('plateforme', models.ForeignKey(help_text="Plateforme où se trouve l'andain", on_delete=django.db.models.deletion.CASCADE, related_name='suivis_stock', to='core.plateforme')),
                ('produit_vente', models.ForeignKey(blank=True, help_text='Produit de vente une fois prêt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suivis_stock', to='core.produitvente')),
                ('utilisateur', models.ForeignKey(blank=True, help_text='Responsable du suivi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suivis_stock', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suivi de stock plateforme',
                'verbose_name_plural': 'Suivis de stock plateforme',
                'db_table': 'suivi_stock_plateforme',
                'ordering': ['plateforme', 'andain_numero'],
                'unique_together': {('plateforme', 'andain_numero')},
            },
        ),
    ]
