# Generated by Django 5.2.1 on 2025-10-21 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_amendementorganique_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FicheAgroPedodeSol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EAP', models.CharField(max_length=100, unique=True, verbose_name='Etude Agro Pedo')),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('projet', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('commanditaire', models.CharField(blank=True, max_length=100, null=True)),
                ('observateur', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_sondage', models.CharField(max_length=50)),
                ('coord_x', models.FloatField(blank=True, null=True)),
                ('coord_y', models.FloatField(blank=True, null=True)),
                ('indication_lieu', models.TextField(blank=True, null=True)),
                ('antecedent_climatique', models.TextField(blank=True, null=True)),
                ('etat_surface', models.TextField(blank=True, null=True)),
                ('couvert_vegetal', models.TextField(blank=True, null=True)),
                ('test_beche', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Fiche agro-pédologique de sol',
                'verbose_name_plural': 'Fiches agro-pédologiques de sol',
                'db_table': 'fiche_agropedodesol',
                'ordering': ['-date', 'nom_sondage'],
            },
        ),
        migrations.CreateModel(
            name='FicheHorizon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=10)),
                ('profondeur', models.CharField(blank=True, max_length=20, null=True)),
                ('texture', models.CharField(blank=True, max_length=50, null=True)),
                ('humidite', models.CharField(blank=True, max_length=50, null=True)),
                ('couleur', models.CharField(blank=True, max_length=50, null=True)),
                ('hydromorphie', models.CharField(blank=True, max_length=50, null=True)),
                ('test_hcl', models.CharField(blank=True, max_length=50, null=True)),
                ('porosite', models.CharField(blank=True, max_length=100, null=True)),
                ('compacite', models.CharField(blank=True, max_length=100, null=True)),
                ('activite_bio', models.CharField(blank=True, max_length=100, null=True)),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('representation_profil', models.CharField(blank=True, max_length=100, null=True)),
                ('echantillon', models.CharField(blank=True, max_length=50, null=True)),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horizons', to='core.ficheagropedodesol')),
            ],
            options={
                'verbose_name': 'Horizon de fiche agro-pédologique',
                'verbose_name_plural': 'Horizons de fiche agro-pédologique',
                'db_table': 'fiche_horizon',
                'ordering': ['fiche', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='FichePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos_fichesagropedosol')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('horizon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.fichehorizon')),
            ],
            options={
                'verbose_name': 'Photo de fiche horizon',
                'verbose_name_plural': 'Photos de fiche horizon',
                'db_table': 'fiche_photo',
                'ordering': ['horizon', 'id'],
            },
        ),
    ]
