# Generated by Django 5.2.1 on 2025-10-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_ficheagropedodesol_fichehorizon_fichephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficheagropedodesol',
            name='EAP',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Etude Agro Pedo'),
        ),
    ]
