# Generated by Django 5.2.1 on 2025-10-27 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_ficheagropedodesol_eap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='melange',
            name='producteur',
        ),
    ]
