# Generated by Django 5.2.1 on 2025-10-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_melange_producteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='melange',
            name='producteur',
            field=models.CharField(default='', help_text='Producteur du produit de vente', max_length=255),
        ),
    ]
