# Generated by Django 5.2.1 on 2025-10-27 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_melange_producteur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='melange',
            name='producteur',
        ),
    ]
