# Generated by Django 5.2.1 on 2025-10-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_remove_melange_producteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='melange',
            name='mcommune',
            field=models.CharField(default='', help_text='Commune du mélange', max_length=100),
        ),
    ]
