# Generated by Django 5.2.1 on 2025-10-27 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_melange_mcommune'),
    ]

    operations = [
        migrations.RenameField(
            model_name='melange',
            old_name='mcommune',
            new_name='commune',
        ),
    ]
