# Generated by Django 5.2.1 on 2025-11-04 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_rename_mcommune_melange_commune'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuiviStockPlateforme',
        ),
    ]
