# Generated by Django 5.2.1 on 2025-11-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_delete_suivistockplateforme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gisement',
            name='type_de_sol',
            field=models.CharField(choices=[('naturel', 'Naturel'), ('remanie', 'Remanié'), ('anthropique', 'Anthropique'), ('autre', 'Autre')], default='naturel', max_length=20),
        ),
    ]
