# Generated by Django 5.2.1 on 2025-11-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_gisement_type_de_sol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gisement',
            name='nom',
            field=models.CharField(blank=True, help_text='Nom du gisement, généré automatiquement si vide.', max_length=255, null=True, unique=True),
        ),
    ]
