# Generated by Django 5.2.1 on 2025-11-26 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_gisement_nom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ficheagropedodesol',
            old_name='test_beche',
            new_name='synthese',
        ),
    ]
