# Generated by Django 5.2.1 on 2025-11-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_rename_test_beche_ficheagropedodesol_synthese'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amendementorganique',
            name='nom',
            field=models.CharField(default='', help_text="Nom de l'émendent organique, généré automatiquement si vide.", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='chantier',
            name='nom',
            field=models.CharField(blank=True, help_text='Nom du chantier, généré automatiquement si vide.', max_length=255, null=True, unique=True, verbose_name='Nom du chantier'),
        ),
        migrations.AlterField(
            model_name='plateforme',
            name='nom',
            field=models.CharField(blank=True, help_text='Nom de la plateforme, généré automatiquement si vide.', max_length=255, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='AnalyseLaboratoire',
        ),
    ]
