# Generated by Django 5.2.1 on 2025-12-18 13:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_amendementorganique_nom_alter_chantier_nom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amendementorganique',
            name='date_semis',
        ),
        migrations.AddField(
            model_name='amendementorganique',
            name='debut_date_fabrication',
            field=models.DateField(default=django.utils.timezone.now, help_text="Date de fabrication de l'émendent organique"),
        ),
    ]
