# Generated by Django 5.2.1 on 2026-01-13 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_remove_amendementorganique_date_semis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MelangeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('ordre_conformite', 'Ordre de conformité'), ('consignes_melange', 'Consignes de mélange'), ('controle_1', 'Contrôle 1'), ('controle_2', 'Contrôle 2'), ('fiche_technique', 'Fiche technique'), ('autre', 'Autre')], default='autre', max_length=50)),
                ('fichier', models.FileField(upload_to='documents/melanges/')),
                ('nom_fichier', models.CharField(blank=True, max_length=255, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('melange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.melange')),
                ('utilisateur', models.ForeignKey(blank=True, help_text="Responsable automatiquement défini à l'utilisateur connecté.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='melange_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
