# Generated by Django 5.2.1 on 2026-01-13 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_melangedocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='melangedocument',
            options={'verbose_name': 'Document de mélange', 'verbose_name_plural': 'Documents de mélange'},
        ),
        migrations.AlterModelTable(
            name='melangedocument',
            table='melange_document',
        ),
    ]
