# Generated by Django 5.2.1 on 2026-01-14 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_melangedocument_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='siret_number',
        ),
    ]
