# Generated by Django 5.2.1 on 2026-01-14 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_remove_customuser_siret_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.DecimalField(decimal_places=2, help_text='En mètres cubes (m3)', max_digits=10, verbose_name='Volume (en m3)')),
                ('date_mise_en_stock', models.DateField(auto_now_add=True, verbose_name='Date de mise en stock')),
                ('etat_stock', models.CharField(choices=[('maturation', 'En maturation'), ('vente', 'En vente'), ('vendu', 'Vendu')], max_length=50)),
                ('melange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='melanges', to='core.melange', verbose_name='Mélange')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'db_table': 'stock',
                'ordering': ['-date_mise_en_stock'],
            },
        ),
    ]
